apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NamespaceDenyIstioInjection
metadata:
  name: namespacedenyistioinjection
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
