apiVersion: v1
kind: Pod
metadata:
  name: containers-resource-constraints-required-test
spec:
  containers:
    - name: hello
      image: busybox:stable
      command: ["sh", "-c", 'echo "Hello, Kubernetes!" && sleep 3600']
      securityContext:
        ####### Deny admission if privileed is set to true
        privileged: false
        ####### Deny admission if nonroot is not set to true
        runAsNonRoot: true
      ####### Deny admission if resources are not set
      resources:
        limits:
          cpu: "300m"
          memory: "4000Mi"
        requests:
          cpu: "100m"
          memory: "1000Mi"
  ####### Deny admission if hostnetwork is set to true
  hostNetwork: true
