apiVersion: v1
kind: Pod
metadata:
  name: containers-resource-constraints-required-test
  namespace: default
spec:
  containers:
    - name: hello
      image: busybox:stable
      command: ["sh", "-c", 'echo "Hello, Kubernetes!" && sleep 3600']
      ####### Deny admission if resources are not set
      resources:
        limits:
          cpu: "300m"
          memory: "400Mi"
        requests:
          cpu: "300m"
          memory: "400Mi"
      securityContext:
        ####### Deny admission if nonroot is not set to true
        runAsNonRoot: true
        runAsUser: 1000
