---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-constraints
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gatekeeper/constraints
    repoURL: https://github.com/gravelmuncha2K/opa-pipelines
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
